### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by VictorCazanave** [VictorCazanave/react-svg-map#17]
- [x] Use SVG files instead of JS files (if possible)
- [x] Provide `CheckboxSVGMap` and `RadioSVGMap` components
- [x] Handle keyboard navigation (a11y)
- [x] Add custom CSS class prop
- [ ] Generate 1 CSS file per map
- [ ] Add more maps (EU, Germany, Spain, Italy, Japan, Korea...)
- [ ] Support Yarn
- [ ] Externalize maps files?

Any thoughts or ideas?

**Comment by VictorCazanave** [comment]
Using SVG files for the maps would make contributions and maintenance easier but:
* the user must add webpack's [svg-inline-loader](https://github.com/webpack-contrib/svg-inline-loader)
* the code becomes more DOM manipulation than "React way"

So for now this idea is put on the side and the other features ( `CheckboxSVGMap`, `RadioSVGMap`, custom CSS class...) will be included in v1.x
